---
- name: Install sinatra gems
  gem:
    executable: /usr/local/bin/gem
    name: '{{ item }}'
    state: latest
    pre_release: no
    include_dependencies: yes
    user_install: no
  with_items: '{{ kernel_sinatra_gems }}'
  become: yes

- name: Set permissions on log file
  file:
    path: '{{ kernel_sinatra_log_file }}'
    state: touch
    owner: '{{ kernel_sinatra_user }}'
    group: '{{ kernel_sinatra_user }}'
    mode: u=rw,g=rw,o=r
  become: yes
