---
- name: Install memcached and prereqs
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  sudo: yes
  with_items: '{{ kernel_memcached_packages }}'

- name: Place config
  template:
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
    force: yes
    src: '{{ kernel_memcached_conf_template }}'
    dest: '{{ kernel_memcached_conf_file }}'
  sudo: yes

- name: Restart memcached
  service:
    name: memcached
    state: restarted
  sudo: yes

- name: Set permissions on log file
  file:
    path: '{{ kernel_memcached_log_file }}'
    state: touch
    owner: '{{ kernel_memcached_user }}'
    group: '{{ kernel_memcached_user }}'
    mode: u=rw,g=rw,o=r
  sudo: yes
