---
- name: Add postgresql apt key
  apt_key:
    state: present
    validate_certs: yes
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  become: yes

- name: Add postgresql apt repository
  apt_repository:
    repo: '{{ item }}'
    state: present
    mode: 420
    update_cache: yes
    validate_certs: yes
  with_items:
    - 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
  become: yes

- name: Install postgresql and prereqs
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  with_items: '{{ kernel_postgresql_packages }}'
  become: yes
