---
- name: Install cassandra
  include: kernel_cassandra_install.yml
  creates: ~{{ kernel_cassandra_cassandra_home }}/bin/cassandra

- name: Update PATH
  lineinfile:
    dest: ~{{ kernel_cassandra_remote_user }}/{{ item }}
    create: yes
    line: 'export PATH="{{ kernel_cassandra_cassandra_home }}/bin:$PATH"'
    state: present
    owner: '{{ kernel_cassandra_remote_user }}'
    group: '{{ kernel_cassandra_remote_user }}'
  with_items: 
    - .bashrc
    - .profile

- name: Create cassandra directories
  file:
    state: directory
    path: '{{ item }}'
    owner: root
    group: '{{ kernel_cassandra_remote_user }}'
    mode: u=rwx,g=rwx,o=rx
  become: yes
  with_items:
    - /var/log/cassandra

- name: Turn off zone_reclaim_mode
  shell: /bin/bash -c "echo 0 > /proc/sys/vm/zone_reclaim_mode"
  become: yes

- name: Cassandra limits a
  lineinfile:
    dest: /etc/security/limits.d/cassandra.conf
    create: yes
    line: '{{ item }}'
    state: present
  with_items:
    - cassandra - memlock unlimited
    - cassandra - nofile 100000
    - cassandra - nproc 32768
    - cassandra - as unlimited
  become: yes

- name: Cassandra limits b
  lineinfile:
    dest: /etc/security/limits.conf
    create: yes
    line: '{{ item }}'
    state: present
  with_items:
    - '* - memlock unlimited'
    - '* - nofile 100000'
    - '* - nproc 32768'
    - '* - as unlimited'
  become: yes

- name: Cassandra limits c
  lineinfile:
    dest: /etc/sysctl.conf
    create: yes
    line: vm.max_map_count = 131072
    state: present
  become: yes

- name: Make the cassandra limits take effect
  shell: /bin/bash -c "sysctl -p {{ item }}"
  become: yes
  with_items:
    - /etc/security/limits.d/cassandra.conf
    - /etc/security/limits.conf

- name: Place config
  template:
    owner: '{{ kernel_cassandra_remote_user }}'
    group: '{{ kernel_cassandra_remote_user }}'
    mode: u=rw,g=r,o=r
    backup: yes
    force: yes
    src: '{{ item.src }}'
    dest: '{{ kernel_cassandra_cassandra_home }}/conf/{{ item.dest }}'
  become: yes
  with_items:
    - { src: logback.xml, dest: logback.xml }

- name: Start cassandra
  shell: /bin/bash -c "nohup {{ kernel_cassandra_cassandra_home }}/bin/cassandra"
  ignore_errors: yes
  become: no

- name: Wait for cassandra to start
  shell: /bin/bash -c "{{ kernel_cassandra_cassandra_home }}/bin/cqlsh -e 'DESCRIBE keyspaces;'"
  register: kernel_cassandra_health
  until: "kernel_cassandra_health.rc == 0"
  retries: 3
  delay: 5
  ignore_errors: yes

- name: Stop cassandra
  shell: /bin/bash -c "kill -9 `ps aux | grep [c]assandra | awk '{print $2}'`"
  ignore_errors: yes
  become: no

- name: Wait for cassandra to stop
  shell: /bin/bash -c "{{ kernel_cassandra_cassandra_home }}/bin/cqlsh -e 'DESCRIBE keyspaces;'"
  register: kernel_cassandra_health
  until: "kernel_cassandra_health.rc != 0"
  retries: 3
  delay: 5
  ignore_errors: yes

- name: Start cassandra
  shell: /bin/bash -c "nohup {{ kernel_cassandra_cassandra_home }}/bin/cassandra"
  ignore_errors: yes
  become: no

- name: Wait for cassandra to start
  shell: /bin/bash -c "{{ kernel_cassandra_cassandra_home }}/bin/cqlsh -e 'DESCRIBE keyspaces;'"
  register: kernel_cassandra_health
  until: "kernel_cassandra_health.rc == 0"
  retries: 3
  delay: 5
  ignore_errors: yes
