---
- name: Add the collectd apt key
  apt_key:
    state: present
    validate_certs: yes
    keyserver: '{{ kernel_collectd_apt_keyserver }}'
    id: '{{ kernel_collectd_apt_key_id }}'
  become: yes


- name: Add the collectd apt repo
  apt_repository:
    repo: '{{ kernel_collectd_apt_repo }}'
    state: present
    mode: 420
    update_cache: yes
    validate_certs: yes
  become: yes


- name: Install collectd packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  with_items: '{{ kernel_collectd_packages }}'
  become: yes


- name: Touch log file
  file:
    path: '{{ kernel_collectd_log_file }}'
    owner: '{{ kernel_collectd_remote_user }}'
    group: '{{ kernel_collectd_remote_user }}'
    mode: u=rw,g=r,o=r
    state: touch
  become: yes


- name: Place passwd
  template:
    owner: '{{ kernel_collectd_remote_user }}'
    group: '{{ kernel_collectd_remote_user }}'
    mode: u=rw,g=,o=
    backup: yes
    force: yes
    src: passwd
    dest: '{{ kernel_collectd_network_plugin_auth_file }}'
  become: yes
  when: kernel_collectd_server_mode


- name: Place config
  template:
    owner: '{{ kernel_collectd_remote_user }}'
    group: '{{ kernel_collectd_remote_user }}'
    mode: u=rw,g=r,o=r
    backup: yes
    force: yes
    src: collectd.conf
    dest: '{{ kernel_collectd_conf_file }}'
  become: yes


- name: Restart collectd
  service:
    name: collectd
    state: restarted
  become: yes
