---
- name: Install nginx and prereqs
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  become: yes
  with_items: '{{ kernel_nginx_packages }}'


- name: Place config
  template:
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
    force: yes
    src: '{{ kernel_nginx_conf_template }}'
    dest: '{{ kernel_nginx_conf_file }}'
  become: yes


- name: Remove some defaults
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  become: yes


- name: Create ssl directory
  file:
    state: directory
    owner: root
    group: root
    path: '{{ kernel_nginx_ssl_directory }}'
    mode: u=rwx,g=rx,o=rx
  become: yes


- name: Place ssl cert
  template:
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    force: yes
    src: '{{ item.src }}'
    dest: '{{ kernel_nginx_ssl_directory }}/{{ item.dest }}'
  become: yes
  with_items:
    - { src: kernel_nginx_cert.crt, dest: cert.crt }
    - { src: kernel_nginx_cert.key, dest: cert.key }
